# @todo: Figure out which versions of windows this will actually build node-pre-gyp bins for.
# windows arch support: 32-bit and 64-bit
# node.js support: Latest stable version, `0.10.x`
# iojs support: Latest stable version
environment:
  node_pre_gyp_accessKeyId:
    secure: Q/MT3KqteKjl23ePjDY9V93G8Ey91LJAOcvJPdEh0i4=
  node_pre_gyp_secretAccessKey:
    secure: pF+hGI1d/+HVKL0EWCGY6YxvRZrfQrLoxfG5AqQTLJ9hJZaiRRQTwU8cwL+4IEuW
  node_pre_gyp_bucket: mongodb-dx-public
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 1.6

platform:
  - x86
  - x64

install:
  - cmd: npm install --build-from-source
  - cmd: node bin/publish-binary-maybe.js

# on_success:
#   @todo: publish-binary-maybe.js should actually be here.

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules

test: OFF
deploy: OFF
build: OFF
